name = "health-reminder"
main = "src/worker.js"
compatibility_date = "2024-06-25"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "health-reminder-prod"

[env.staging]
name = "health-reminder-staging"

# Custom domain configuration (optional)
# routes = [
#   { pattern = "your-domain.com/*", zone_name = "your-domain.com" }
# ]

# Environment variables (if needed)
# [vars]
# ENVIRONMENT = "production"

# KV namespace bindings (if you need persistent storage)
# [[kv_namespaces]]
# binding = "HEALTH_REMINDER_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Build configuration
[build]
command = ""
cwd = ""
watch_dir = ""

# Limits and settings (CPU limits not supported on Free plan)
# [limits]
# cpu_ms = 50
